<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
      <ProjectReference Include="..\CsiHub.Core\CsiHub.Core.csproj" />
      <ProjectReference Include="..\CsiHub.Ingestion\CsiHub.Ingestion.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <RootNamespace>CsiHub</RootNamespace>
        <AssemblyName>CsiHub</AssemblyName>
    </PropertyGroup>

</Project>
