; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 921600
lib_compat_mode = soft
lib_ldf_mode = deep+
build_flags =
    -I include
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CFG_TUD_CDC_EP_BUFSIZE=512
    -D CFG_TUD_CDC_TX_BUFSIZE=4096
    -D CFG_TUD_CDC_RX_BUFSIZE=512
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    fastled/FastLED @ ^3.6.0
    sparkfun/SparkFun BNO08x Cortex Based IMU @ ^1.0.6

; Node 0 (Leader)
[env:node0]
upload_port = COM3  ; Replace with your actual port

; Node 1 (Follower)
[env:node1]
upload_port = COM4  ; Replace with your actual port

; Node 2 (Follower)
[env:node2]
upload_port = COM5  ; Replace with your actual port
